defaults:
  - sort_of_clevr_base
  - _self_

name: sort_of_clevr
seed: 0              
root: ./data

train_size: 36000 # number of scenes -> total samples num scenes * 3 * nb_questions
test_size: 1000 # val size also
nb_questions: 10 # per subtype per image (x3 subtypes)
t_subtype: -1 # -1 = random ternary subtype

dir: ${dataset.name}-seed${dataset.seed}-train${dataset.train_size}-test${dataset.test_size}-q${dataset.nb_questions}-t${dataset.t_subtype}
